[notebook]
dir = "~/notes"

[note]
language = "en"
default-title = "Untitled"
filename = "{{id}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 8
id-case = "lower"

[extra]
author = "Shivan"

[group.standup]
paths = ["notes/standup"]

[group.standup.note]
filename = "{{format-date now}}"
extension = "md"
template = "standup.md"

[group.daily]
paths = ["notes/daily"]

[group.daily.note]
filename = "{{format-date now}}"
extension = "md"
template = "daily.md"

[group.deepdive]
paths = ["notes/deepdive"]

[group.deepdive.note]
filename = "{{format-date now}}"
extension = "md"
template = "deepdive.md"

[format.markdown]
hashtags = true
colon-tags = true

[tool]
editor = "nvim"
pager = "less -FIRX"
fzf-preview = "bat -p --color always {-1}"

[filter]
recents = "--sort created- --created-after 'last two weeks'"

[alias]

edlast = "zk edit --limit 1 --sort modified- $argv"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
lucky = "zk list --quiet --format full --sort random --limit 1"
ls = "zk edit --interactive"

config = 'nvim "$HOME/.dotfiles/zk/config.toml"'

standup = 'zk new --no-input "$ZK_NOTEBOOK_DIR/standup"'
ls-standup = 'zk edit "$ZK_NOTEBOOK_DIR/standup" --sort created- --interactive'

deepdive = 'zk new --no-input "$ZK_NOTEBOOK_DIR/deepdive"'
ls-deepdive = 'zk edit "$ZK_NOTEBOOK_DIR/deepdive" --sort created- --interactive'

update = "cd $ZK_NOTEBOOK_DIR; git add -A; git commit -am 'updating'; git push; cd -"

[lsp]
[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"
missing-backlink = { level = "warning", position = "bottom" }
