[note]
language = "en"
default-title = "Untitled"
filename = "{{id}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 8
id-case = "lower"

[extra]
author = "Shivan"

[group.standup]
paths = ["notes/standup"]

[group.standup.note]
filename = "{{format-date now}}"
extension = "md"
template = "standup.md"


[format.markdown]
hashtags = true
colon-tags = true

[tool]
editor = "nvim"
pager = "less -FIRX"
fzf-preview = "bat -p --color always {-1}"

[filter]
recents = "--sort created- --created-after 'last two weeks'"

[alias]

edlast = "zk edit --limit 1 --sort modified- $argv"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
lucky = "zk list --quiet --format full --sort random --limit 1"
ls = "zk edit --interactive"
t = "zk edit --interactive --tag $argv"

config = 'nvim "$HOME/.dotfiles/zk/config.toml"'

standup = 'zk new --no-input "$ZK_NOTEBOOK_DIR/Standup"'
ls-standup = 'zk edit "$ZK_NOTEBOOK_DIR/Standup" --sort created- --interactive'

update = "cd $ZK_NOTEBOOK_DIR; git add -A; git commit -am 'updating'; git push; cd -"

[lsp]
[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
